### ISSUE TITLE
[ROADMAP] Custom Chips

### ISSUE THREAD

**Issue by Jozott00** [Jozott00/wokwi-intellij#38]
You can load custom chips to the simulation by adding a `[[chip]]` sections to your `wokwi.toml` configuration. The following example will load a chip from `chip/inverter.chip.wasm` and make it available under the name chip-inverter in Wokwi's diagram:

```toml
[[chip]]
name = 'inverter'  # To use the chip in diagram.json, add a part with "chip-inverter" type.
binary = 'chips/inverter.chip.wasm'
```

[Custom chips - Wokwi docs](https://docs.wokwi.com/vscode/project-config#custom-chips)
